language: go

go:
  - 1.8
  - 1.9
  - '1.10'

before_install:
  - go get -u -v github.com/golang/lint/golint
  - go get -u -v honnef.co/go/tools/cmd/megacheck

before_script:
  - go vet
  - golint
  - megacheck
