version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/configure

    steps:
      - checkout
      - run:
          name: Run go mod
          command: |
            go mod download
            go mod vendor
      - run:
          name: Run vet
          command: go vet
      - run:
          name: Run lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status
      - run:
          name: Run staticcheck
          command: |
            go get -u honnef.co/go/tools/cmd/staticcheck
            staticcheck
      - run:
          name: Run tests
          command: go test -v

workflows:
  version: 2
  build:
    jobs:
      - build
